### ISSUE TITLE
v-model's value doesn't change

### ISSUE THREAD

**Issue by Boevsson** [vue-bulma/datepicker#44]
`<datepicker v-model="publishedAt"></datepicker>`

the value of 'publishedAt' doesn't change when date is picked

**Comment by Reechee88** [comment]
any update?

**Comment by luventa** [comment]
fixed in v1.3.4

**Comment by cashlion** [comment]
I'm still having this issue with 1.3.4. The datepicker will read the initial value but it won't update it when I select a different date.

**Comment by luventa** [comment]
@cashlion sorry, made a stupid mistake yesterday. Now fixed.
Also this a [demo](https://github.com/luventa/datepicker-demo)

**Comment by cashlion** [comment]
Great, thanks!
